# Generated by Django 6.0.4 on 2026-04-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_payout_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='bank_account_id',
            field=models.CharField(default='test_account', max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['key', 'merchant'], name='payouts_ide_key_c50227_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['merchant'], name='payouts_led_merchan_a837b5_idx'),
        ),
    ]
